# Site settings
course_name: Nature Inspired Design in Computing
course_description: "When scientists get stuck on a particular design or algorithm to solve a problem, they often take inspiration from nature. By studying and mimicking natural processes, computer scientists have developed innovative techniques and algorithms to solve complex problems, optimize resources, and enhance the performance and efficiency of computing systems. In this seminar, we will explore some fundamental design principles of nature, such as the behavior of ants, the structure of trees, and the organization of neurons, and how they can be applied to the design of computing systems. This course can provide you with tools to think outside the box and approach problems from a different perspective. By learning from nature's strategies, you can develop the ability to come up with creative and innovative solutions to challenges in computer science and other disciplines."
course_semester: "Fall 2023"

baseurl: "/FYS-NID" # the subpath of your site, e.g. /blog/
url: "https://arjun23496.github.io/" # the base hostname & protocol for your site

schoolname: "Manning College of Information and Computer Sciences"
schoolurl: "https://www.umass.edu/"
twitter_username: ArjunK018 

address: |
    College of Information and Computer Sciences
    University of Massachusetts Amherst

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
